=== Tom1101/efrei-xml/TP1/step2/addressbook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
    <!-- element address book with address book type -->
    <xs:element name="address_book" type="address_bookType"/>

    <!-- address book type -->
    <xs:complexType name="address_bookType">
        <xs:sequence>
            <xs:element type="contactsType" name="contacts"/>
        </xs:sequence>
    </xs:complexType>

    <!-- address type -->
    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element type="xs:string" name="street_number"/>
            <xs:element type="xs:string" name="street_name"/>
            <xs:element type="xs:string" name="city"/>
            <xs:element type="xs:string" name="zip"/>
            <xs:element type="xs:string" name="country"/>
        </xs:sequence>
    </xs:complexType>

    <!-- list of address -->
    <xs:complexType name="addressesType">
        <xs:sequence>
            <xs:element type="addressType" name="address"/>
        </xs:sequence>
    </xs:complexType>

    <!-- phone type -->
    <xs:complexType name="phoneType">
        <xs:sequence>
            <xs:element type="xs:string" name="number"/>
        </xs:sequence>
        <!-- phone type is required -->
        <xs:attribute type="xs:string" name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="fax"/>
                    <xs:enumeration value="mobile"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- list of phone -->
    <xs:complexType name="phonesType">
        <xs:sequence>
            <xs:element type="phoneType" name="phone" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- contact type -->
    <xs:complexType name="contactType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="surname"/>
            <xs:element type="phonesType" name="phones"/>
            <xs:element type="addressesType" name="addresses"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="type" use="required"/>
    </xs:complexType>

    <!-- list of contact -->
    <xs:complexType name="contactsType">
        <xs:sequence>
            <xs:element type="contactType" name="contact"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Tom1101/efrei-xml/TP1/step2/addressbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<address_book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="addressbook.xsd">
    <contacts>
        <contact type="person">
            <name>test</name>
            <surname>eza</surname>
            <phones>
                <phone type="mobile">
                    <number>123124</number>
                </phone>
                <phone type="fax">
                    <number>1232312</number>
                </phone>
            </phones>
            <addresses>
                <address>
                    <street_number>12</street_number>
                    <street_name>DZ1OH</street_name>
                    <city>AAZC</city>
                    <zip>12392</zip>
                    <country>France</country>
                </address>
            </addresses>
        </contact>
    </contacts>
</address_book>
